export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
// export const LOAD_CATEGORY_NAMES = 'LOAD_CATEGORY_NAMES';
export const GET_CATEGORY_NAMES_SUCCESS = 'GET_CATEGORY_NAMES_SUCCESS';
// export const LOAD_CATEGORY_DETAILS = 'LOAD_CATEGORY_DETAILS';
export const GET_CATEGORY_DETAILS_SUCCESS = 'GET_CATEGORY_DETAILS_SUCCESS';
// export const GET_CATEGORY_DETAILS_FAIL = 'GET_CATEGORY_DETAILS_FAIL';
