export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const GET_CATEGORY_NAMES_SUCCESS = 'GET_CATEGORY_NAMES_SUCCESS';
export const GET_CATEGORY_DETAILS_SUCCESS = 'GET_CATEGORY_DETAILS_SUCCESS';
export const SET_QUESTION = 'SET_QUESTION';
export const CLEAR_QUESTION = 'CLEAR_QUESTION';
